#!/bin/dash -e
# This file is a build file for the cpfos package management tool
# of the Hardened Linux distribution.

TMP=/tmp/hlhs
CWD="`pwd`"
PKG=/tmp/pkg/hlhs


# first create the _hlhs.tgz
rm -rf $TMP
rm -rf $PKG
mkdir -p $TMP
mkdir -p $PKG
mkdir $PKG/install
cp -r $CWD/_hlhs/* $TMP/
# remove editor and subversion files!
cd $TMP
rm -rf `find . -name '*~' -o -name '.svn'`
mv -v * $PKG/

# now the postinst.sh script
cp -v $CWD/postinst.sh $PKG/install/
chmod 755 $PKG/install/postinst.sh

