#!/bin/dash -e

cd $PKG
cp -r $CWD/src/* ./

rm -rf `find . -name '.svn' -o -name '*~'`

mkdir -p $PKG/usr/man/man8
cat $CWD/doc/cpfos.8 | gzip -9c > $PKG/usr/man/man8/cpfos.8.gz
cat $CWD/postinst.sh > $PKG/install/postinst.sh

chown root:root *

chmod og-rwx var/cache/packages
chmod og-wx etc/cpfos.conf
chmod ugo+x sbin/*
chmod u+x install/*.sh

