#!/bin/bash -e
# (bash gives us more possibilities)
# 
# rpkg is distributed under the following license:
# 
# Copyright (c) 2007 Steffen Wendzel <steffen (at) wendzel (dot) de>
# Written 2007 by Steffen Wendzel
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Developers note for the coding style:
# 	BIG_CHAR_VAR   <-- var is exported
#	small_char_var <-- only used within this script

# How does it work? -- An important note for all developers
# ---------------------------------------------------------
# rpkg currently does this steps in the following order:
# 
# - check if the pkg is given by $1 and if it is installed
# - remove files (but make sure that you only remove empty dirs)
# - remove pkg's files in /var/cache/packages

# global vars
pkgcache=/var/cache/packages

# check usage
if [ "$1" = "" ]; then
	echo "usage: $0 <package name>"
	exit 1
fi

# check if pkg is installed
if [ ! -f ${pkgcache}/${1}.inf -o ! -f ${pkgcache}/${1}.files ]; then
	echo "$1 is not installed."
	exit 1
fi

# remove every file included in the package and use reverse sort since
# we need the directory names at the END of the listing. also take care
# about the files in /install
for ifile in `cat ${pkgcache}/${1}.files | awk '{print $NF}' | \
		egrep -v '^./install/' | sort -r`; do
	if [ -f /$ifile ]; then
		rm -v /$ifile
	elif [ -d /$ifile ]; then
		# count files in dir to check if it is empty
		num_files=`/bin/ls /$ifile | wc -l`
		if [ "$num_files" = "0" ]; then
			rmdir -v /$ifile
		fi
	fi
done

rm ${pkgcache}/${1}.inf ${pkgcache}/${1}.files

exit 0

