#!/bin/bash -e
# 
# spkg is distributed under the following license:
# 
# Copyright (c) 2007 Steffen Wendzel <steffen (at) wendzel (dot) de>
# Written 2007 by Steffen Wendzel
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Developers note for the coding style:
# BIG_CHAR_VAR   <-- var is exported
#small_char_var <-- only used within this script

# How does it work? -- An important note for all developers
# ---------------------------------------------------------
# spkg currently does this steps in the following order:
# 
# - find pkgfile
# - try to find the given keyword in the package name or in the description
#   of a package

if [ "$UPDATE_DIR" = "" ]; then
	echo "UPDATE_DIR not set. please use cpfos"
	exit 1
fi

pkgfile=${UPDATE_DIR}/updates/pkgfile

if [ -f $pkgfile ]; then
	egrep $1 $pkgfile
else
	echo "${pkgfile}: not found. exiting."
	exit 1
fi

exit 0

